"""second migration

Revision ID: b464bc288961
Revises: 493ad2ea8d92
Create Date: 2022-09-12 08:30:26.513122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b464bc288961'
down_revision = '493ad2ea8d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tested_positive', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('country', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('deaths', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('series', sa.String(length=150), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drone')
    # ### end Alembic commands ###
